apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-spawner-config
data:
  config.toml: |
    [logging]
    level = "{{ .Values.config.logging.level }}"

    [zendesk]
    subdomain = "{{ .Values.config.zendeskSubdomain }}"

    [teamwork]
    domain = "{{ .Values.config.teamworkDomain }}"
    project_id = "{{ .Values.config.teamworkProjectId }}"
    task_list_id = "{{ .Values.config.teamworkTaskListId }}"