apiVersion: v1
kind: Secret
metadata:
  name: task-spawner-secrets
  labels:
    app: task-spawner
type: Opaque
data:
  ZENDESK_SUBDOMAIN: {{ .Values.secrets.zendeskSubdomain | b64enc }}
  ZENDESK_API_TOKEN: {{ .Values.secrets.zendeskApiToken | b64enc }}
  TEAMWORK_DOMAIN: {{ .Values.secrets.teamworkDomain | b64enc }}
  TEAMWORK_API_TOKEN: {{ .Values.secrets.teamworkApiToken | b64enc }}
  TEAMWORK_PROJECT_ID: {{ .Values.secrets.teamworkProjectId | b64enc }}
