apiVersion: v1
kind: Secret
metadata:
  name: ticket-spawner-secrets
type: Opaque
stringData:
  ZENDESK_EMAIL: {{ .Values.secrets.zendeskEmail | quote }}
  ZENDESK_API_TOKEN: {{ .Values.secrets.zendeskApiToken | quote }}
  TEAMWORK_API_TOKEN: {{ .Values.secrets.teamworkApiToken | quote }}
  ZENDESK_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
