apiVersion: v1
kind: Service
metadata:
  name: task-spawner
  labels:
    app: task-spawner
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: task-spawner